on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies (Ubuntu)
      run: |
        sudo apt-get update
        sudo apt-get install -y clang ninja-build cmake build-essential

    - name: Build on Ubuntu (debug)
      run: |
        mkdir -p ${{github.workspace}}/build
        cd ${{github.workspace}}/build
        cmake .. \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_BUILD_TYPE=Debug \
          -DBUILD_TEST=ON \
          -G Ninja
        cmake --build . --config Debug

    - name: Build on Ubuntu (release)
      run: |
        mkdir -p ${{github.workspace}}/build
        cd ${{github.workspace}}/build
        cmake .. \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TEST=ON \
          -G Ninja
        cmake --build . --config Release