on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang ninja-build cmake build-essential
    - name: Create Build Directory
      run: mkdir -p ${{github.workspace}}/build
    - name: Configure CMake with Clang and Ninja
      working-directory: ${{github.workspace}}/build
      run: |
        cmake .. \
          -DCMAKE_C_COMPILER=clang \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_TESTING=ON \
          -G Ninja
    - name: Build with Ninja
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --config Release
    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ctest -C Release --output-on-failure
    - name: iris-compiler
      working-directory: ${{github.workspace}}/build
      run: cmake --build . --target iris-compiler
